# Pandas - Series and DataFrames
- It is a powerful Python Library mainly used for data analysis and data cleaning. It provides 2 Primary data structures : **Series & DataFrames**.
- Series : One - Dimensional array like structure
- DataFrames : 2-D, Size mutable, and potentially a heterogenous tabular Data Structure with labelled axes (Rows, Cols)

In [18]:
import pandas as pd

## Series:

In [19]:
# Series from an array 
# This prints the default index of the series which is 0,1,2,3 and the values of the series which are 1,2,3,4

data = [1,2,3,4]

series = pd.Series(data)
print('Series: \n', series)

Series:
 0    1
1    2
2    3
3    4
dtype: int64

In [20]:
# Series from a Dictionary
# This prints keys as the index of the series which is a,b,c,d and the values of the series which are 1,2,3,4

data = {'a':1, 'b':2, 'c':3, 'd':4}
series_dict = pd.Series(data)

print('Series from a Dictionary: \n', series_dict)

Series from a Dictionary:
 a    1
b    2
c    3
d    4
dtype: int64

In [21]:
# Creating Custom Indexes

data = [1,2,3,4]
index = ['a', 'b', 'c', 'd']

pd.Series(data, index = index)

a    1
b    2
c    3
d    4
dtype: int64

## DataFrames:

In [27]:
data = {
    'Name' : ['Alice', 'Bob', 'Charlie', 'David'],
    'Age' : [25, 30, 35, 40],
    'City' : ['New York', 'Los Angeles', 'Chicago', 'Houston']
}
df = pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
<class 'pandas.DataFrame'>

In [23]:
# Converting a DataFrame to a Numpy Array

import numpy as np
np.array(df)

array([['Alice', 25, 'New York'],
       ['Bob', 30, 'Los Angeles'],
       ['Charlie', 35, 'Chicago'],
       ['David', 40, 'Houston']], dtype=object)

In [24]:
df = pd.read_csv('bank_data.csv')
df.head(5)      # This will print the first 5 rows of the dataframe. You can also specify the number of rows you want to print by passing an argument to the head() method. For example, df.head(10) will print the first 10 rows of the dataframe.
                #For example, df.head(10) will print the first 10 rows of the dataframe.

print('--------------')
df.tail(5)     # This will print the last 5 rows of the dataframe. You can also specify the number of rows you want to print by passing an argument to the tail() method. For example, df.tail(10) will print the last 10 rows of the dataframe.

--------------

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status,age_group,income_bracket,credit_category
44620,27,male,Associate,47971,6,RENT,15000,MEDICAL,15.66,0.31,3,645,No,1,26-35,Medium (30-60K),Fair
44621,37,female,Associate,65800,17,RENT,9000,HOMEIMPROVEMENT,14.07,0.14,11,621,No,1,36-45,High (60-100K),Fair
44622,33,male,Associate,56942,7,RENT,2771,DEBTCONSOLIDATION,10.02,0.05,10,668,No,1,26-35,Medium (30-60K),Fair
44623,29,male,Bachelor,33164,4,RENT,12000,EDUCATION,13.23,0.36,6,604,No,1,26-35,Medium (30-60K),Fair
44624,24,male,High School,51609,1,RENT,6665,DEBTCONSOLIDATION,17.05,0.13,3,628,No,1,18-25,Medium (30-60K),Fair

In [28]:
df['Name']

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: str

 ### Loc
 - This will print the first row of the dataframe. You can also specify the index of the row you want to print by passing an argument to the loc[] method. For example, df.loc[1] will print the second row of the dataframe.

In [ ]:
df.loc[0]

Name       Alice
Age           25
City    New York
Name: 0, dtype: object

### iLoc: 
- This will print the first row of the dataframe. You can also specify the index of the row you want to print by passing an argument to the iloc[] method. For example, df.iloc[1] will print the second row of the dataframe.

In [31]:
df.iloc[0]

Name       Alice
Age           25
City    New York
Name: 0, dtype: object

## Data Manupilation with Data Frames:

In [38]:
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston

## Adding a New Column to a DataFrame

In [39]:
df['Salary'] = [50000, 60000, 70000, 80000]
df

      Name  Age         City  Salary
0    Alice   25     New York   50000
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000
3    David   40      Houston   80000

## Removing a Column from the DataFrame
- the code below is throwing an error because the drop() method does not modify the original dataframe by default. We have to set axis = 1 for it to check the col indexes otherwise by default i.e axis = 0 it check the row indexes and it will not have the col salary hence it is throwing the error.

- The code below will drop the Salary column from the dataframe but it will not change the original dataframe. If you want to change the original dataframe, you can use the inplace parameter and set it to True. For example, df.drop('Salary', inplace=True) will drop the Salary column from the dataframe and change the original dataframe.

In [40]:
df.drop('Salary', axis=1)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston

In [41]:
# The fix
print(df)
df.drop('Salary', axis =1, inplace = True)
df

      Name  Age         City  Salary
0    Alice   25     New York   50000
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000
3    David   40      Houston   80000

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston

## Modifying the indivisual elements of the Df:

In [43]:
df['Age'] = df['Age'] + 1
df

      Name  Age         City
0    Alice   27     New York
1      Bob   32  Los Angeles
2  Charlie   37      Chicago
3    David   42      Houston

In [46]:
# Displaying the DataTypes of each Col in the DataFrame
df.dtypes

Name      str
Age     int64
City      str
dtype: object

In [47]:
# Describing the DataFrame
df.describe()

             Age
count   4.000000
mean   34.500000
std     6.454972
min    27.000000
25%    30.750000
50%    34.500000
75%    38.250000
max    42.000000